title: Agenda des communautés tech toulousaines
lang: fr-FR
site: https://toulouse-tech-hub.fr
baseurl: 
#theme: 

collections:
  groups:
    output: true
    permalink: /groups/:slug/
  confs:
    output: false
  events:
    output: false

defaults:
  - scope:
      path: ""
      type: groups
    values:
      layout: group
