title: Agenda des communautés tech toulousaines
lang: fr-FR
site: https://toulouse-tech-hub.fr
baseurl: 
#theme: 

# Seuil d'archivage des évènements (en jours) - doit correspondre à la valeur dans update.cs
archive_days: 365

collections:
  groups:
    output: false
  confs:
    output: false
  events:
    output: false
