name: 🐛 Signaler un bug
description: Signaler une erreur sur le site ou dans les données
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Décrivez simplement ce qui ne va pas, on s'occupe du reste ! 👍

  - type: textarea
    id: description
    attributes:
      label: Quel est le problème ?
      description: Expliquez ce qui ne fonctionne pas. N'hésitez pas à ajouter des captures d'écran en les glissant-déposant ici.
      placeholder: |
        Exemple :
        - L'événement "Python Meetup" du 15 mars n'apparaît pas sur le calendrier
        - Le lien vers la page Meetup de GDG Toulouse est cassé
        - Le logo de la communauté Rust n'apparaît pas sur mobile
        - Il manque une communauté dans la liste : ...
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: Lien concerné (si applicable)
      placeholder: https://toulouse-tech-hub.fr/...
