name: 💡 Suggestion d'amélioration
description: Proposer une nouvelle fonctionnalité ou amélioration
title: "[Feature] "
labels: ["💡 suggestion"]
body:
  - type: markdown
    attributes:
      value: |
        Une idée pour améliorer le site ? On est tout ouïe ! 👂

  - type: textarea
    id: description
    attributes:
      label: Votre idée
      description: Décrivez librement votre suggestion. Pas besoin de formalisme, expliquez juste ce qui serait cool d'avoir !
      placeholder: |
        Exemple :
        - Ce serait super d'avoir un filtre par type de techno (JavaScript, Python, etc.)
        - J'aimerais pouvoir m'abonner uniquement aux événements d'une communauté spécifique
        - Une carte interactive avec les lieux des événements serait pratique
        - Ajouter un mode sombre pour le site
        
        N'hésitez pas à mentionner des exemples de sites qui font ça bien si vous en connaissez !
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: Je peux contribuer au développement si besoin
